version: "3.9"

services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    hostname: oracle_host
    container_name: oracle_container
    # platform: linux/amd64
    environment:
      - ORACLE_SID=XE
      - ORACLE_PWD=secret
    ports:
      - "1521:1521"
      - "5500:5500"
    # volumes:
    #   - ./oracle_data:/opt/oracle/oradata

  keycloak:
    container_name: keycloak_container
    hostname: keycloak_host
    build:
      context: .
      dockerfile: dockerfile/keycloak-Dockerfile
    networks:
      - integration_network
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - TZ=Iran/Tehran
      - KC_HTTP_RELATIVE_PATH=/auth
    depends_on:
      - oracle
    ports:
      - "9001:8443"
      - "9000:8080"
    command:
      - start-dev
      - --https-certificate-file=/keycloak/config/ssl/cert.pem
      - --https-certificate-key-file=/keycloak/config/ssl/key.pem
      - --import-realm
    volumes:
      - ./ssl/cert.pem:/keycloak/config/ssl/cert.pem
      - ./ssl/key.pem:/keycloak/config/ssl/key.pem
      - ./import:/opt/keycloak/data/import

  camunda:
    build:
      context: .
      dockerfile: dockerfile/camunda-Dockerfile
    container_name: camunda_container
    hostname: camunda_host
    networks:
      - integration_network
    ports:
      - 8085:8080
    env_file:
      - ./env/camunda.env
    depends_on:
      - keycloak
    restart: always
    volumes:
      - ./config/default.yml:/camunda/configuration/default.yml
      - ./config/production.yml:/camunda/configuration/production.yml

networks:
  integration_network:
    driver: bridge
